### PR TITLE
[Logging] Add remote IP log context on authn failure

### LINKED ISSUE #1014: [Logging] Add remote IP log context on authn failure
Hi,

I'm opening this issue to start a discussion before eventually contributing.

I'm interested in combining `fail2ban` with pigallery2 🔒 
For this to work, `fail2ban` would require access to the remote IP of a client that fails authentication.

Would you be okay to add such context to the log messages in [user authn middleware](https://github.com/bpatrik/pigallery2/blob/master/src/backend/middlewares/user/AuthenticationMWs.ts) ?
For users behind _reverse proxies_ this may require end-user to enable [express trust proxy](https://expressjs.com/en/guide/behind-proxies.html). This may require a new configuration setting for that 🤷 

Thanks for this awesome software, this is perfect for home requirements 👍 !

Regards

### PR DESCRIPTION
**Pull request by riton**
Fixes #1014 

Add support for [express trust proxy](https://expressjs.com/en/guide/behind-proxies.html) and remote client IP in failed authentication logs.

### CODE REVIEW

**Comment by riton** [comment]
Hi @bpatrik 

This is an initial implementation of #1019 
This has not been tested yet.

Feel free to comment !

Regards

File: src/common/config/private/PrivateConfig.ts [hunk 1]
```diff
@@ -933,6 +933,15 @@ export class ServerServiceConfig extends ClientServiceConfig {
...
   sessionTimeout: number = 1000 * 60 * 60 * 24 * 7; // in ms
 
+  @ConfigProperty({
+    tags: {
+      name: $localize`Trust Proxy`,
+      priority: ConfigPriority.underTheHood,
+    },
+    description: $localize`Should the backend trust proxies to extract remote Client IP`,
+  })
+  trustProxy: string = "false";
```
Comment (bpatrik) [inline src/common/config/private/PrivateConfig.ts:943]: is this a boolean? then please use a bollean value (i,e:  trustProxy: boolean= false;)

File: src/common/config/private/PrivateConfig.ts [hunk 2]
```diff
@@ -933,6 +933,15 @@ export class ServerServiceConfig extends ClientServiceConfig {
   })
   sessionTimeout: number = 1000 * 60 * 60 * 24 * 7; // in ms
 
+  @ConfigProperty({
+    tags: {
+      name: $localize`Trust Proxy`,
+      priority: ConfigPriority.underTheHood,
```
Comment (bpatrik) [inline src/common/config/private/PrivateConfig.ts:939]: maybe add here the github issue id reference? see example in the rest of the config.

File: src/common/config/private/PrivateConfig.ts (hunk 1 above)
Comment (bpatrik) [reply src/common/config/private/PrivateConfig.ts:943]: ahh I see how this works. Reading up on this: https://expressjs.com/en/guide/behind-proxies.html

This value sets the number of hops. Can you improve on that? its not clear form the name and the description what is happening.
Like: changing the config name or separating into a sub config. like: "class trustedProxyConfig {enable:boolean, trustedHop:number}"

**Comment by bpatrik** [comment]
generally looks good. I had some confusion about the naming. Can you improve on that?

Than you for your contribution!

**Comment by bpatrik** [comment]
than you for your contribution!
